/**
 * The point of no return: the last moment a press still saves you from the wall.
 *
 * A drifting ship pointed at a side boundary has a deadline, and until now
 * nothing on screen said where it was. The playtest of 2026-08-22 recorded the
 * consequence: a run ended `LOST — OFF COURSE` with full fuel and two planets on
 * screen, and from the player's seat the failure read as arbitrary. Note 40 is
 * the same fact from the simulation's side — a grab was accepted at the left
 * wall, entered `clear` with periapsis ten seconds away, and the ship left the
 * field at t=2.78s with the button still held.
 *
 * WHY THIS ANSWERS BY SIMULATING RATHER THAN BY REASONING
 *
 * "Can I still be saved" has no closed form. The answer depends on which body
 * `grabTarget` would offer at that instant, whether the grab is refused by the
 * crash cone, whether it classifies as a flyby, how much fuel is left to brake
 * with, and how much of that fuel the drift will have regenerated by the time
 * the ship gets there. Every one of those is already decided by `stepSim`, and a
 * second implementation of any of them is two things that can only drift apart —
 * the reasoning `drawOrbitCurve` records for not recomputing the settle easing.
 *
 * So this clones the state and plays it. It is slow the way a truth is slow, and
 * it is cached by its caller rather than made cheap by being made approximate.
 *
 * WHAT COUNTS AS RESCUED
 *
 * Press and hold, and the ship's velocity toward that wall reaches zero before
 * the run ends. Not "reaches a settled orbit" — a braked flyby that arcs back
 * out is a rescue, and it is the one the fire is lit for, so demanding a settle
 * would call the game's best moment a death. And not "survived N seconds", which
 * was the first proposal here: it needs an N, and an N is a number nobody can
 * measure the right value of. Turn-around needs no constant at all.
 *
 * THE BUBBLE NEEDS NO SPECIAL CASE. An anomaly suspends the side boundary, so a
 * drift that crosses the wall inside one simply does not end there — the
 * projection runs on and finds the real ending out the far side. Asking `stepSim`
 * where the run ends, instead of asking geometry where the wall is, gets the
 * anomaly rule for free and cannot fall out of step with it.
 */
import type { SimConfig } from './config.ts';
import type { Capture, SimState } from './types.ts';
import { NO_INPUT } from './types.ts';
import { shipWorldPos, stepSim } from './step.ts';
import { fieldBounds } from './world.ts';

/** One point on the projected path, and whether a press there still saves you. */
export interface ScarSample {
  /** Seconds from now. */
  t: number;
  x: number;
  y: number;
  /**
   * A press and hold here turns the ship away from the wall before it crosses.
   *
   * Not monotonic along the path, deliberately. `grabTarget` refuses inside the
   * crash cone and offers a different body as the ship travels, so the live
   * stretch can have holes in it — sliding past a planet at speed is the shape
   * that produces one. The consumer draws them.
   */
  live: boolean;
}

export interface RescueScar {
  /** Which boundary the drift is committed to: -1 left, +1 right. */
  side: -1 | 1;
  /** Seconds until the run would end at it. */
  tEnd: number;
  /**
   * The last press that still rescues. Null when none does — the deadline has
   * already passed, or there never was one.
   */
  cross: { x: number; y: number; t: number } | null;
  /** The projected drift path, ship first, ending where the run would. */
  path: ScarSample[];
  /**
   * Where the ship would fly if it pressed AT the cross and held: one world
   * position per tick, from the press to the moment it turns away.
   *
   * Empty when there is no cross. It exists so a consumer can measure something
   * about the rescue this mark is offering — what the fire would be worth, in
   * `src/score/` — without simulating the same flight a second time, and without
   * `src/sim/` having to learn what a point is. The simulation hands over a
   * trajectory; scoring is somebody else's word for it.
   */
  flight: Array<{ x: number; y: number }>;
}

export interface ScarOptions {
  /**
   * How far ahead to look for the wall, in seconds. A guard, not a threshold:
   * a ship whose ending is further away than this has no scar, because there is
   * nothing to aim at yet. How far ahead it is DRAWN is the renderer's ramp and
   * a different question.
   */
  horizon: number;
  /**
   * Smallest gap between evaluated press-points, in ticks. Sets the finest
   * resolution the holes can be drawn at.
   */
  stride: number;
  /**
   * Most press-points to evaluate, however long the drift is.
   *
   * A cost bound, and the one that matters most: each evaluation is a whole
   * simulated capture, and the drift ahead of a shallow approach can be six
   * seconds long. Unbounded, the worst call in the corpus evaluated 121 presses
   * and took 46ms — three frames at 60Hz on a desktop, and the author reported the
   * consequence as "slowdown due to rendering... more noticeable at the edges",
   * which is exactly where this stops taking its cheap refusal.
   *
   * The stride widens to fit rather than the path being truncated, so a long
   * approach is sampled coarsely rather than only near the ship. Holes get
   * blockier on those; nothing else changes.
   */
  maxSamples: number;
  /**
   * Ticks a hypothetical capture is followed before it is given up on.
   *
   * Reached only by a capture that neither dies nor turns, which is a shape that
   * should not exist; resolving it as NOT rescued is the conservative direction,
   * and conservative pulls the cross earlier.
   *
   * 360 and not the 900 it started at. Measured, a winning flight runs a median
   * 89 ticks and 223 at p90, so six seconds is far past anything real — and every
   * evaluation that neither dies nor turns pays the whole budget, which made it
   * the second-largest term in the worst call.
   */
  captureBudget: number;
}

export const DEFAULT_SCAR_OPTIONS: Readonly<ScarOptions> = Object.freeze({
  horizon: 6,
  stride: 3,
  maxSamples: 40,
  captureBudget: 360,
});

const PRESS = Object.freeze({ held: true, pressed: true, released: false });
const HOLD = Object.freeze({ held: true, pressed: false, released: false });

/**
 * A working copy the projection can ruin.
 *
 * Bodies are shared by reference and only the array is copied: nothing under
 * `src/sim/` mutates a body, and a projection that did would be corrupting the
 * world the player is flying in. The array copy is what makes that a compile-time
 * accident rather than a live one.
 */
function cloneState(s: SimState): SimState {
  const cap: Capture | null = s.capture
    ? { ...s.capture, orbit: s.capture.orbit ? { ...s.capture.orbit } : null }
    : null;
  return {
    tick: s.tick,
    ship: { ...s.ship },
    capture: cap,
    bodies: s.bodies.slice(),
    fuel: s.fuel,
    highWaterY: s.highWaterY,
    ending: { ...s.ending },
    holdConsumed: s.holdConsumed,
    chargedT: s.chargedT,
    cameFrom: s.cameFrom,
    telemetry: { ...s.telemetry },
  };
}

/** World x-velocity, wherever the ship currently keeps it. */
function worldVx(s: SimState): number {
  return s.capture ? s.capture.vx : s.ship.vx;
}

/**
 * Does a press and hold from here turn away from `side` before the run ends?
 *
 * The hold is held forever, which is both what a player does in this situation
 * and self-limiting: the flyby brake runs only while `fuel > 0`, so a low tank
 * shortens the answer honestly instead of the prediction over-promising.
 *
 * A refused grab needs no branch. `stepSim` starts a capture only on the pressed
 * edge, so a refusal leaves the ship drifting with the button uselessly down —
 * exactly what the player would experience — and the drift ends where it was
 * always going to.
 */
function rescues(
  from: SimState,
  cfg: SimConfig,
  dt: number,
  side: 1 | -1,
  budget: number,
  record: Array<{ x: number; y: number }> | null = null,
): boolean {
  const s = cloneState(from);
  stepSim(s, cfg, PRESS, dt);
  for (let i = 0; i < budget; i++) {
    if (record) {
      const p = shipWorldPos(s);
      record.push({ x: p.x, y: p.y });
    }
    if (s.ending.active) return false;
    if (worldVx(s) * side <= 0) return true;
    stepSim(s, cfg, HOLD, dt);
  }
  return false;
}

/**
 * The same answer, `secs` later, without simulating anything again.
 *
 * A DRIFT TAKES NO INPUT, so the projection a call produced stays true as the
 * ship flies along it: every sample is a world point with a fixed verdict, and
 * the cross is a place rather than a countdown. What changes as the ship advances
 * is only which samples are still ahead of it and how long is left.
 *
 * That makes a full recompute per tick almost pure waste, and the waste was
 * measurable: a simulating call runs a median 1.4ms and up to 19ms on a desktop,
 * three to five times that on a phone, which is what the author saw as "slowdown
 * ... more noticeable at the edges". The edges are where the cheap refusal stops
 * applying.
 *
 * Returns null once the projection is spent — the ending it was describing is now
 * behind, so there is nothing left to advance and the caller must ask again.
 *
 * IT DOES NOT KNOW WHEN IT IS WRONG. Anything that changes the ship's velocity —
 * a press, a release, a respawn — invalidates the projection, and the caller is
 * responsible for noticing. `app/main.ts` recomputes on every capture transition
 * and on a timer besides.
 */
export function advanceScar(scar: RescueScar, secs: number): RescueScar | null {
  const tEnd = scar.tEnd - secs;
  if (tEnd <= 0) return null;
  const path = scar.path.filter((p) => p.t - secs >= 0).map((p) => ({ ...p, t: p.t - secs }));
  const crossT = scar.cross ? scar.cross.t - secs : 0;
  return {
    side: scar.side,
    tEnd,
    // A cross the ship has reached is a cross it is now past, which is the same
    // thing `rescueScar` reports by returning none: the last press that could
    // have worked is behind.
    cross: scar.cross && crossT >= 0 ? { ...scar.cross, t: crossT } : null,
    path,
    flight: scar.flight,
  };
}

/**
 * The scar for a drifting ship, or null when there is nothing to draw.
 *
 * Null covers every case where the question is not being asked: mid-capture
 * (where the escape is a release, not a grab), during the ending hold, when the
 * drift reaches no ending inside `horizon`, and when the ending it reaches is not
 * a side wall — a ship about to hit a planet or fall behind the floor is dying of
 * something this cue has no opinion about.
 */
export function rescueScar(
  state: SimState,
  cfg: SimConfig,
  dt: number,
  opts: ScarOptions = DEFAULT_SCAR_OPTIONS,
): RescueScar | null {
  if (state.capture || !state.ship.alive || state.ending.active) return null;

  // ---- cheap refusal, so the common case never pays for the projection
  //
  // Drift is a straight line at constant velocity plus a burst that decays
  // linearly to nothing, so the furthest the ship can travel sideways inside the
  // horizon has a closed form. If neither wall is inside that reach there is no
  // side ending to find, and this can only return null where the projection
  // would have. It is an early-out, not a second opinion.
  const fb = fieldBounds(cfg, state.bodies);
  const reach =
    Math.abs(state.ship.vx) * opts.horizon +
    (Math.abs(state.ship.burstX) * Math.min(opts.horizon, cfg.boostBurstDecay)) / 2;
  if (state.ship.x - reach > fb.left && state.ship.x + reach < fb.right) return null;

  // ---- project the drift once, keeping positions per tick and states sparsely
  //
  // A state copy costs a structural clone including the bodies array, and only
  // the sampled ticks are ever resumed from — keeping one at every tick was 361
  // copies for the 40 that got used. The first pass finds the ending and nothing
  // else; the second walks the same drift again and clones only where it stops.
  // Walking twice is far cheaper than copying 360 times.
  const maxTicks = Math.ceil(opts.horizon / dt);
  const s = cloneState(state);
  let endTick = -1;
  let endReason: SimState['ending']['reason'] = 'impact';
  let endX = 0;
  for (let i = 1; i <= maxTicks; i++) {
    stepSim(s, cfg, NO_INPUT, dt);
    if (s.ending.active) {
      endTick = i;
      endReason = s.ending.reason;
      endX = s.ending.x;
      break;
    }
  }
  if (endTick < 0) return null; // nothing ahead worth marking
  if (endReason !== 'out-of-bounds') return null;

  // Which wall, read off where the run actually ended rather than off the
  // heading: `outX` and `outY` share one ending, and a ship that left over the
  // top while drifting sideways has no side deadline to mark.
  const side: 1 | -1 | 0 = endX > fb.right ? 1 : endX < fb.left ? -1 : 0;
  if (side === 0) return null;

  // ---- evaluate a press at each sampled tick, re-walking the drift as we go
  //
  // The stride widens so the whole approach is covered by at most `maxSamples`
  // evaluations. A six-second drift is then sampled every 9 ticks rather than
  // every 3, which costs resolution in the holes and bounds the work.
  const stride = Math.max(opts.stride, Math.ceil((endTick + 1) / opts.maxSamples));
  const path: ScarSample[] = [];
  let lastLive = -1;
  let lastLiveState: SimState | null = null;
  let firstDeadAfter = -1;
  const walk = cloneState(state);
  for (let i = 0; i <= endTick; i += stride) {
    while (walk.tick - state.tick < i) stepSim(walk, cfg, NO_INPUT, dt);
    const live = rescues(walk, cfg, dt, side, opts.captureBudget);
    path.push({ t: i * dt, x: walk.ship.x, y: walk.ship.y, live });
    if (live) {
      lastLive = i;
      lastLiveState = cloneState(walk);
      firstDeadAfter = -1;
    } else if (firstDeadAfter < 0) {
      firstDeadAfter = i;
    }
  }

  // ---- refine the last live tick to the tick, so the cross is a stable world
  // point rather than one that hops by a stride as the ship advances into it
  let cross: RescueScar['cross'] = null;
  const flight: Array<{ x: number; y: number }> = [];
  if (lastLive >= 0 && lastLiveState) {
    // Walk the tick or two past the last live sample rather than bisecting into a
    // table of stored states. The gap is one stride, so this is a handful of
    // evaluations either way, and it needs no clone of every tick to index into.
    const hi = firstDeadAfter >= 0 ? firstDeadAfter : Math.min(endTick, lastLive + stride);
    let best = lastLiveState;
    let bestTick = lastLive;
    const probe = cloneState(lastLiveState);
    for (let i = lastLive + 1; i < hi; i++) {
      stepSim(probe, cfg, NO_INPUT, dt);
      if (!rescues(probe, cfg, dt, side, opts.captureBudget)) break;
      best = cloneState(probe);
      bestTick = i;
    }
    cross = { x: best.ship.x, y: best.ship.y, t: bestTick * dt };
    // One more flight, this time kept. It is the rescue the mark is offering, and
    // re-flying it costs a single capture against the dozens the search already
    // ran — much less than making every evaluation carry an array it would throw
    // away.
    rescues(best, cfg, dt, side, opts.captureBudget, flight);
  }

  return { side, tEnd: endTick * dt, cross, path, flight };
}
