/**
 * The point of no return: the last moment a press still saves you from the wall.
 *
 * A drifting ship pointed at a side boundary has a deadline, and until now
 * nothing on screen said where it was. The playtest of 2026-08-22 recorded the
 * consequence: a run ended `LOST — OFF COURSE` with full fuel and two planets on
 * screen, and from the player's seat the failure read as arbitrary. Note 40 is
 * the same fact from the simulation's side — a grab was accepted at the left
 * wall, entered `clear` with periapsis ten seconds away, and the ship left the
 * field at t=2.78s with the button still held.
 *
 * WHY THIS ANSWERS BY SIMULATING RATHER THAN BY REASONING
 *
 * "Can I still be saved" has no closed form. The answer depends on which body
 * `grabTarget` would offer at that instant, whether the grab is refused by the
 * crash cone, whether it classifies as a flyby, how much fuel is left to brake
 * with, and how much of that fuel the drift will have regenerated by the time
 * the ship gets there. Every one of those is already decided by `stepSim`, and a
 * second implementation of any of them is two things that can only drift apart —
 * the reasoning `drawOrbitCurve` records for not recomputing the settle easing.
 *
 * So this clones the state and plays it. It is slow the way a truth is slow, and
 * it is cached by its caller rather than made cheap by being made approximate.
 *
 * WHAT COUNTS AS RESCUED
 *
 * Press and hold, and the ship's velocity toward that wall reaches zero before
 * the run ends. Not "reaches a settled orbit" — a braked flyby that arcs back
 * out is a rescue, and it is the one the fire is lit for, so demanding a settle
 * would call the game's best moment a death. And not "survived N seconds", which
 * was the first proposal here: it needs an N, and an N is a number nobody can
 * measure the right value of. Turn-around needs no constant at all.
 *
 * THE BUBBLE NEEDS NO SPECIAL CASE. An anomaly suspends the side boundary, so a
 * drift that crosses the wall inside one simply does not end there — the
 * projection runs on and finds the real ending out the far side. Asking `stepSim`
 * where the run ends, instead of asking geometry where the wall is, gets the
 * anomaly rule for free and cannot fall out of step with it.
 */
import type { SimConfig } from './config.ts';
import type { Capture, SimState } from './types.ts';
import { NO_INPUT } from './types.ts';
import { stepSim } from './step.ts';
import { fieldBounds } from './world.ts';

/** One point on the projected path, and whether a press there still saves you. */
export interface ScarSample {
  /** Seconds from now. */
  t: number;
  x: number;
  y: number;
  /**
   * A press and hold here turns the ship away from the wall before it crosses.
   *
   * Not monotonic along the path, deliberately. `grabTarget` refuses inside the
   * crash cone and offers a different body as the ship travels, so the live
   * stretch can have holes in it — sliding past a planet at speed is the shape
   * that produces one. The consumer draws them.
   */
  live: boolean;
}

export interface RescueScar {
  /** Which boundary the drift is committed to: -1 left, +1 right. */
  side: -1 | 1;
  /** Seconds until the run would end at it. */
  tEnd: number;
  /**
   * The last press that still rescues. Null when none does — the deadline has
   * already passed, or there never was one.
   */
  cross: { x: number; y: number; t: number } | null;
  /** The projected drift path, ship first, ending where the run would. */
  path: ScarSample[];
}

export interface ScarOptions {
  /**
   * How far ahead to look for the wall, in seconds. A guard, not a threshold:
   * a ship whose ending is further away than this has no scar, because there is
   * nothing to aim at yet. How far ahead it is DRAWN is the renderer's ramp and
   * a different question.
   */
  horizon: number;
  /** Ticks between evaluated press-points. Sets the resolution of the holes. */
  stride: number;
  /**
   * Ticks a hypothetical capture is followed before it is given up on. Reached
   * only by a capture that neither dies nor turns, which is a shape that should
   * not exist; resolving it as NOT rescued is the conservative direction, and
   * conservative pulls the cross earlier.
   */
  captureBudget: number;
}

export const DEFAULT_SCAR_OPTIONS: Readonly<ScarOptions> = Object.freeze({
  horizon: 6,
  stride: 3,
  captureBudget: 900,
});

const PRESS = Object.freeze({ held: true, pressed: true, released: false });
const HOLD = Object.freeze({ held: true, pressed: false, released: false });

/**
 * A working copy the projection can ruin.
 *
 * Bodies are shared by reference and only the array is copied: nothing under
 * `src/sim/` mutates a body, and a projection that did would be corrupting the
 * world the player is flying in. The array copy is what makes that a compile-time
 * accident rather than a live one.
 */
function cloneState(s: SimState): SimState {
  const cap: Capture | null = s.capture
    ? { ...s.capture, orbit: s.capture.orbit ? { ...s.capture.orbit } : null }
    : null;
  return {
    tick: s.tick,
    ship: { ...s.ship },
    capture: cap,
    bodies: s.bodies.slice(),
    fuel: s.fuel,
    highWaterY: s.highWaterY,
    ending: { ...s.ending },
    holdConsumed: s.holdConsumed,
    chargedT: s.chargedT,
    cameFrom: s.cameFrom,
    telemetry: { ...s.telemetry },
  };
}

/** World x-velocity, wherever the ship currently keeps it. */
function worldVx(s: SimState): number {
  return s.capture ? s.capture.vx : s.ship.vx;
}

/**
 * Does a press and hold from here turn away from `side` before the run ends?
 *
 * The hold is held forever, which is both what a player does in this situation
 * and self-limiting: the flyby brake runs only while `fuel > 0`, so a low tank
 * shortens the answer honestly instead of the prediction over-promising.
 *
 * A refused grab needs no branch. `stepSim` starts a capture only on the pressed
 * edge, so a refusal leaves the ship drifting with the button uselessly down —
 * exactly what the player would experience — and the drift ends where it was
 * always going to.
 */
function rescues(
  from: SimState,
  cfg: SimConfig,
  dt: number,
  side: 1 | -1,
  budget: number,
): boolean {
  const s = cloneState(from);
  stepSim(s, cfg, PRESS, dt);
  for (let i = 0; i < budget; i++) {
    if (s.ending.active) return false;
    if (worldVx(s) * side <= 0) return true;
    stepSim(s, cfg, HOLD, dt);
  }
  return false;
}

/**
 * The scar for a drifting ship, or null when there is nothing to draw.
 *
 * Null covers every case where the question is not being asked: mid-capture
 * (where the escape is a release, not a grab), during the ending hold, when the
 * drift reaches no ending inside `horizon`, and when the ending it reaches is not
 * a side wall — a ship about to hit a planet or fall behind the floor is dying of
 * something this cue has no opinion about.
 */
export function rescueScar(
  state: SimState,
  cfg: SimConfig,
  dt: number,
  opts: ScarOptions = DEFAULT_SCAR_OPTIONS,
): RescueScar | null {
  if (state.capture || !state.ship.alive || state.ending.active) return null;

  // ---- cheap refusal, so the common case never pays for the projection
  //
  // Drift is a straight line at constant velocity plus a burst that decays
  // linearly to nothing, so the furthest the ship can travel sideways inside the
  // horizon has a closed form. If neither wall is inside that reach there is no
  // side ending to find, and this can only return null where the projection
  // would have. It is an early-out, not a second opinion.
  const fb = fieldBounds(cfg, state.bodies);
  const reach =
    Math.abs(state.ship.vx) * opts.horizon +
    (Math.abs(state.ship.burstX) * Math.min(opts.horizon, cfg.boostBurstDecay)) / 2;
  if (state.ship.x - reach > fb.left && state.ship.x + reach < fb.right) return null;

  // ---- project the drift, keeping a resumable copy at every tick
  const maxTicks = Math.ceil(opts.horizon / dt);
  const track: SimState[] = [cloneState(state)];
  const s = cloneState(state);
  let endTick = -1;
  for (let i = 1; i <= maxTicks; i++) {
    stepSim(s, cfg, NO_INPUT, dt);
    track.push(cloneState(s));
    if (s.ending.active) {
      endTick = i;
      break;
    }
  }
  if (endTick < 0) return null; // nothing ahead worth marking
  if (track[endTick]!.ending.reason !== 'out-of-bounds') return null;

  // Which wall, read off where the run actually ended rather than off the
  // heading: `outX` and `outY` share one ending, and a ship that left over the
  // top while drifting sideways has no side deadline to mark.
  const endX = track[endTick]!.ending.x;
  const side: 1 | -1 | 0 = endX > fb.right ? 1 : endX < fb.left ? -1 : 0;
  if (side === 0) return null;

  // ---- evaluate a press at every `stride`th tick along it
  const path: ScarSample[] = [];
  let lastLive = -1;
  let firstDeadAfter = -1;
  for (let i = 0; i <= endTick; i += opts.stride) {
    const at = track[i]!;
    const live = rescues(at, cfg, dt, side, opts.captureBudget);
    path.push({ t: i * dt, x: at.ship.x, y: at.ship.y, live });
    if (live) {
      lastLive = i;
      firstDeadAfter = -1;
    } else if (firstDeadAfter < 0) {
      firstDeadAfter = i;
    }
  }

  // ---- refine the last live tick to the tick, so the cross is a stable world
  // point rather than one that hops by a stride as the ship advances into it
  let cross: RescueScar['cross'] = null;
  if (lastLive >= 0) {
    let lo = lastLive;
    let hi = firstDeadAfter >= 0 ? firstDeadAfter : Math.min(endTick, lastLive + opts.stride);
    while (hi - lo > 1) {
      const mid = (lo + hi) >> 1;
      if (rescues(track[mid]!, cfg, dt, side, opts.captureBudget)) lo = mid;
      else hi = mid;
    }
    const at = track[lo]!;
    cross = { x: at.ship.x, y: at.ship.y, t: lo * dt };
  }

  return { side, tEnd: endTick * dt, cross, path };
}
