/**
 * Capture (or verify) the golden physics baseline.
 *
 * The live equality test is the primary gate while Stage 0 holds, because
 * index.html is in-repo and immutable. This baseline exists for Stage 2: once a
 * PORT-NOTE fix deliberately changes behaviour, the port no longer matches the
 * prototype, and this file becomes the reference the change is diffed against.
 *
 *   node tools/capture-golden.ts           write golden/physics-v1.json
 *   node tools/capture-golden.ts --check   verify the port still matches it
 *
 * Everything is addressed by integer tick and stored at full precision. No
 * rounding, no wall-clock times.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { runPrototype } from './prototype-harness.ts';
import { runPort } from '../test/run-port.ts';
import { SCENARIOS } from '../test/scenarios.ts';
import { compare } from './compare.ts';
import { PROTOTYPE_CONFIG, FIXED_DT } from '../src/sim/config.ts';
import { DESIGN_H, DESIGN_W } from '../src/sim/world.ts';
import type { TrajectorySample } from '../src/sim/serialize.ts';

const OUT = fileURLToPath(new URL('../golden/physics-v1.json', import.meta.url));

interface Golden {
  schema: 1;
  note: string;
  capturedFrom: string;
  dt: number;
  design: { w: number; h: number };
  config: typeof PROTOTYPE_CONFIG;
  scenarios: Array<{ name: string; samples: TrajectorySample[] }>;
}

function build(): Golden {
  return {
    schema: 1,
    note: 'Reference trajectories. Generated by tools/capture-golden.ts. Tick-indexed, full precision.',
    capturedFrom: 'index.html (immutable prototype), driven headlessly at fixed dt',
    dt: FIXED_DT,
    design: { w: DESIGN_W, h: DESIGN_H },
    config: PROTOTYPE_CONFIG,
    scenarios: SCENARIOS.map((sc) => ({ name: sc.name, samples: runPrototype(sc, FIXED_DT) })),
  };
}

const check = process.argv.includes('--check');

if (!check) {
  mkdirSync(fileURLToPath(new URL('../golden', import.meta.url)), { recursive: true });
  writeFileSync(OUT, JSON.stringify(build(), null, 1) + '\n');
  const g = build();
  const ticks = g.scenarios.reduce((n, s) => n + s.samples.length, 0);
  console.log(`wrote golden/physics-v1.json — ${g.scenarios.length} scenarios, ${ticks} ticks`);
} else {
  const golden = JSON.parse(readFileSync(OUT, 'utf8')) as Golden;
  let failures = 0;
  if (golden.dt !== FIXED_DT) {
    console.error(`dt changed: golden ${golden.dt} vs current ${FIXED_DT}`);
    failures++;
  }
  for (const [key, value] of Object.entries(PROTOTYPE_CONFIG)) {
    const was = (golden.config as unknown as Record<string, number | boolean>)[key];
    if (was !== value) {
      console.error(`config drift: ${key} golden=${was} current=${value}`);
      failures++;
    }
  }
  for (const gs of golden.scenarios) {
    const sc = SCENARIOS.find((s) => s.name === gs.name);
    if (!sc) {
      console.error(`scenario missing from the matrix: "${gs.name}"`);
      failures++;
      continue;
    }
    const r = compare(gs.samples, runPort(sc, FIXED_DT), 0);
    const ok = r.maxPositionDelta === 0 && r.maxVelocityDelta === 0 && r.phaseMismatches === 0;
    if (!ok) {
      console.error(
        `DRIFT "${gs.name}": Δpos=${r.maxPositionDelta.toExponential(3)} ` +
          `Δvel=${r.maxVelocityDelta.toExponential(3)} phase≠=${r.phaseMismatches}` +
          (r.first ? ` first at tick ${r.first.tick} (${r.first.field})` : ''),
      );
      failures++;
    }
  }
  if (failures) {
    console.error(`\n${failures} golden check failure(s).`);
    process.exit(1);
  }
  console.log(`golden check passed — ${golden.scenarios.length} scenarios match`);
}
